# Generated by Django 3.2.4 on 2021-06-13 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210613_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='movie_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.events'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.events'),
        ),
    ]
