# Generated by Django 3.2.4 on 2021-06-13 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210613_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.events'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.events'),
        ),
    ]
